variable "region" {
  description = "OCI home region (Always Free capacity is home-region-only)."
  type        = string
  default     = "ap-mumbai-1"
}

variable "tenancy_ocid" {
  description = "OCI tenancy OCID."
  type        = string
}

variable "user_ocid" {
  description = "OCI user OCID (the API-key user)."
  type        = string
}

variable "fingerprint" {
  description = "Fingerprint of the OCI API signing key."
  type        = string
}

variable "private_key_path" {
  description = "Path to the OCI API signing private key (PEM)."
  type        = string
}

variable "compartment_ocid" {
  description = "Compartment to provision into. Defaults to the tenancy (root) compartment."
  type        = string
  default     = ""
}

variable "ad_index" {
  description = "Index into the availability domains list (free tier may only have capacity in one)."
  type        = number
  default     = 0
}

variable "node_count" {
  description = "Number of A1.Flex nodes. 1 = single-node cluster. 2 = control plane + worker."
  type        = number
  default     = 1
}

variable "ocpus" {
  description = "OCPUs per node (Always Free pool: 4 OCPU / 24 GB total across all A1 instances)."
  type        = number
  default     = 2
}

variable "memory_gb" {
  description = "Memory in GB per node (Always Free pool: 4 OCPU / 24 GB total)."
  type        = number
  default     = 12
}

variable "ssh_public_key_path" {
  description = "Path to the SSH public key used to log into the nodes as ubuntu."
  type        = string
}

variable "home_cidr" {
  description = "CIDR allowed to reach SSH (22) and the k3s API (6443)."
  type        = string
  default     = "0.0.0.0/0"
}

variable "k3s_version" {
  description = "Pinned k3s version installed by cloud-init."
  type        = string
  default     = "v1.31.5+k3s1"
}

variable "k3s_token" {
  description = "Shared cluster token. Autogenerated if empty (see main.tf)."
  type        = string
  default     = ""
  sensitive   = true
}
